/**
 * 選択タグだけから SQL を組み立てる（完全一致・加算型）
 * タグを1つ足すとその句が付き、選んでいない句は付けない。
 * プレースホルダは テーブル1 / 列名1 など日本語で出す。
 */
function localizeSqlPlaceholders(sql) {
  var map = {
    table_name_exists: "テーブル2",
    table_name_in: "テーブル2",
    table_name_lat: "テーブル2",
    table_name_3: "テーブル3",
    table_name_2: "テーブル2",
    table_name: "テーブル1",
    column_name_lat_key: "列名3",
    column_name_distinct: "列名1",
    column_name_exists: "列名3",
    column_name_search: "列名1",
    column_name_regex: "列名1",
    column_name_array: "列名1",
    column_name_null: "列名1",
    column_name_json: "列名1",
    column_name_cast: "列名1",
    column_name_cmp: "列名1",
    column_name_any: "列名1",
    column_name_all: "列名1",
    column_name_not: "列名1",
    column_name_num: "列名2",
    column_name_lat: "列名2",
    column_name_in: "列名3",
    column_name_4: "列名4",
    column_name_3: "列名3",
    column_name_2: "列名2",
    column_name: "列名1",
    column_list: "列名1",
    group_column_2: "列名2",
    group_column: "列名1",
    order_column_lat: "並べ替え列",
    order_column: "並べ替え列",
    alias_name_2: "別名2",
    alias_name: "別名1",
    where_filter_agg: "集計条件",
    where_condition_2: "条件2",
    where_condition: "条件1",
    operator_having: "演算子",
    operator_scalar: "演算子",
    operator_any: "演算子",
    operator_all: "演算子",
    operator_not: "演算子",
    operator: "演算子",
    value_having: "値1",
    value_start: "開始値",
    value_regex: "'パターン'",
    value_array: "値1",
    value_limit: "件数",
    value_rate: "倍率",
    value_like: "'%キーワード%'",
    value_json: "{\"キー\": \"値\"}",
    value_end: "終了値",
    value_any: "(値1, 値2)",
    value_all: "(値1, 値2)",
    value_not: "値1",
    value_2: "値2",
    value: "値1",
    direction: "並び順",
  };
  return String(sql).replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, function (_, key) {
    return Object.prototype.hasOwnProperty.call(map, key) ? map[key] : key;
  });
}

function buildExactSqlFromIntent(sel) {
  var sql = buildExactSqlFromIntentRaw(sel);
  return sql == null ? sql : localizeSqlPlaceholders(sql);
}

function buildExactSqlFromIntentRaw(sel) {
  function H(id) { return sel.has(id); }

  // ---------- 単独系 ----------
  if (H("begin") && sel.size === 1) return "BEGIN;";
  if (H("commit") && sel.size === 1) return "COMMIT;";
  if (H("rollback") && sel.size === 1) return "ROLLBACK;";
  if (H("savepoint") && sel.size === 1) return "SAVEPOINT {{alias_name}};";

  if (H("index") && !H("fetch") && !H("insert") && !H("update") && !H("delete")) {
    return "CREATE INDEX {{alias_name}}\n  ON {{table_name}} ({{column_name}});";
  }
  if ((H("create_table") || H("constraints")) && !H("fetch") && !H("insert")) {
    return "CREATE TABLE {{table_name}} (\n" +
      "  {{column_name}} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
      "  {{column_name_2}} TEXT NOT NULL" +
      (H("constraints") ? ",\n  CONSTRAINT {{alias_name}} CHECK ({{column_name_3}} >= 0)" : "") +
      "\n);";
  }

  // ---------- DML ----------
  if (H("multi_insert")) {
    return "INSERT INTO {{table_name}} ({{column_name}})\nVALUES\n  ({{value}}),\n  ({{value_2}})" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("upsert")) {
    return "INSERT INTO {{table_name}} ({{column_name}})\nVALUES ({{value}})\n" +
      "ON CONFLICT ({{column_name_2}})\nDO UPDATE SET {{column_name_3}} = EXCLUDED.{{column_name_3}}" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("insert") && !H("insert_select")) {
    return "INSERT INTO {{table_name}} ({{column_name}})\nVALUES ({{value}})" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("update_cte")) {
    return "WITH {{alias_name}} AS (\n  SELECT {{column_name}}\n  FROM {{table_name}}" +
      (needWhere() ? "\n  WHERE {{where_condition}}" : "") +
      "\n)\nUPDATE {{table_name}} AS t\nSET {{column_name_2}} = {{value}}\n" +
      "FROM {{alias_name}} AS x\nWHERE t.{{column_name}} = x.{{column_name}}" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("update_join") || (H("update") && (H("join") || H("left_join")))) {
    return "UPDATE {{table_name}} AS e\nSET {{column_name}} = d.{{column_name_2}}\n" +
      "FROM {{table_name_2}} AS d\nWHERE e.{{column_name_3}} = d.{{column_name_3}}" +
      (needWhere() ? "\n  AND ({{where_condition}})" : "") +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("update")) {
    return "UPDATE {{table_name}}\nSET {{column_name}} = {{value}}\nWHERE {{where_condition}}" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("delete_join")) {
    return "DELETE FROM {{table_name}} AS e\nUSING {{table_name_2}} AS d\n" +
      "WHERE e.{{column_name_3}} = d.{{column_name_3}}" +
      (needWhere() ? "\n  AND ({{where_condition}})" : "") +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }
  if (H("delete")) {
    return "DELETE FROM {{table_name}}\nWHERE {{where_condition}}" +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }

  function needWhere() {
    return H("filter") || H("compare") || H("like") || H("case_insensitive") ||
      H("is_null") || H("regex") || H("json") || H("array") || H("any_op") || H("all_op") ||
      H("not_op") || H("exists") || H("not_exists") || H("compound_where") ||
      H("scalar_subquery") || H("correlated_subquery") || H("multirow_subquery") || H("no_match");
  }

  function hasAgg() {
    return H("sum") || H("avg") || H("count") || H("max") || H("min") ||
      H("count_distinct") || H("filter_agg") || H("ratio_agg") || H("filter_clause") ||
      H("after_group") || H("per_group") || H("group_multi");
  }

  function hasWin() {
    return H("window") || H("win_row_number") || H("win_rank") || H("win_dense_rank") ||
      H("win_lag") || H("win_lead") || H("win_running_total") || H("win_moving_avg") || H("win_group_compare");
  }

  function hasJoin() {
    return H("join") || H("left_join") || H("right_join") || H("full_join") ||
      H("cross_join") || H("self_join") || H("multi_join") || H("no_match") || H("lateral");
  }

  // INSERT…SELECT（取得系タグと併用可）
  if (H("insert_select")) {
    var innerSel = buildSelectBody();
    return "INSERT INTO {{table_name}} ({{column_list}})\n" + innerSel.replace(/;$/, "") +
      (H("returning") ? "\nRETURNING *" : "") + ";";
  }

  if (H("view")) {
    return "CREATE VIEW {{alias_name}} AS\n" + buildSelectBody();
  }

  var body = buildSelectBody();

  if (H("explain_analyze")) return "EXPLAIN ANALYZE\n" + body;
  if (H("explain")) return "EXPLAIN\n" + body;

  return body;

  // ---------- SELECT 本体 ----------
  function buildSelectBody() {
    var useAlias = H("alias") || hasJoin() || H("correlated_subquery") || H("scalar_subquery") ||
      H("select_subquery") || H("from_subquery") || hasWin();
    var p = useAlias ? "e." : "";

    // FROM
    var frm;
    if (H("generate_series") && !hasJoin() && !hasAgg() && !H("from_subquery")) {
      frm = "FROM generate_series({{value_start}}, {{value_end}}) AS e(gs)";
      p = "e.";
      useAlias = true;
    } else if (H("self_join")) {
      frm = "FROM {{table_name}} AS e\nINNER JOIN {{table_name}} AS m\n  ON e.{{column_name_2}} = m.{{column_name_3}}";
    } else if (H("multi_join")) {
      frm = "FROM {{table_name}} AS e\nINNER JOIN {{table_name_2}} AS d\n  ON e.{{column_name_3}} = d.{{column_name_3}}\n" +
        "INNER JOIN {{table_name_3}} AS x\n  ON e.{{column_name_4}} = x.{{column_name_4}}";
    } else if (H("cross_join")) {
      frm = "FROM {{table_name}} AS e\nCROSS JOIN {{table_name_2}} AS d";
    } else if (H("left_join") || H("no_match")) {
      frm = "FROM {{table_name}} AS e\nLEFT JOIN {{table_name_2}} AS d\n  ON e.{{column_name_3}} = d.{{column_name_3}}";
    } else if (H("right_join")) {
      frm = "FROM {{table_name}} AS e\nRIGHT JOIN {{table_name_2}} AS d\n  ON e.{{column_name_3}} = d.{{column_name_3}}";
    } else if (H("full_join")) {
      frm = "FROM {{table_name}} AS e\nFULL OUTER JOIN {{table_name_2}} AS d\n  ON e.{{column_name_3}} = d.{{column_name_3}}";
    } else if (H("join")) {
      frm = "FROM {{table_name}} AS e\nINNER JOIN {{table_name_2}} AS d\n  ON e.{{column_name_3}} = d.{{column_name_3}}";
    } else if (H("from_subquery")) {
      frm = "FROM (\n  SELECT {{column_name}} AS col, {{group_column}} AS grp, {{column_name_num}} AS num\n" +
        "  FROM {{table_name}}\n) AS e";
    } else if (useAlias) {
      frm = "FROM {{table_name}} AS e";
    } else {
      frm = "FROM {{table_name}}";
    }

    if (H("lateral")) {
      if (frm.indexOf(" AS e") === -1 && frm.indexOf("{{table_name}}") !== -1 && !useAlias) {
        frm = "FROM {{table_name}} AS e";
        p = "e.";
        useAlias = true;
      }
      frm += "\nLEFT JOIN LATERAL (\n" +
        "  SELECT lat.{{column_name_lat}}\n  FROM {{table_name_lat}} AS lat\n" +
        "  WHERE lat.{{column_name_lat_key}} = " + p + "{{column_name_lat_key}}\n" +
        "  ORDER BY lat.{{order_column_lat}} {{direction}}\n" +
        "  LIMIT 1\n) AS r ON TRUE";
    }

    // SELECT list
    var parts = [];
    var onlyAgg = hasAgg() && !H("per_group") && !H("after_group") && !H("group_multi") && !hasWin() &&
      !H("all_columns") && !H("select_columns") && !H("calc_column") && !H("const_column") &&
      !H("select_subquery") && !H("unique") && !H("distinct_on") && !H("cast");

    if (H("generate_series") && frm.indexOf("generate_series") !== -1) {
      parts.push("e.gs AS {{column_name}}");
    } else if (H("all_columns") && !hasAgg() && !hasWin()) {
      parts.push("*");
    } else {
      if (H("const_column")) parts.push("'const' AS const_label");
      if (H("calc_column")) parts.push("(" + p + "{{column_name_num}} * {{value_rate}}) AS calculated");
      if (H("cast")) parts.push("(" + p + "{{column_name_cast}})::text AS casted");
      if (H("select_subquery")) {
        parts.push("(SELECT COUNT(*) FROM {{table_name_2}} AS s WHERE s.{{column_name_3}} = " +
          p + "{{column_name_3}}) AS sub_cnt");
      }

      // 行の表示列（集計のみのときは付けない）
      if (!onlyAgg) {
        if (H("unique") && !hasAgg()) {
          parts.unshift((H("distinct_on") ? "DISTINCT ON (" + p + "{{group_column}}) " : "DISTINCT ") +
            p + "{{column_name}}");
        } else if (H("distinct_on") && !hasAgg()) {
          parts.unshift("DISTINCT ON (" + p + "{{group_column}}) " + p + "{{column_name}}");
        } else if (hasAgg() && (H("per_group") || H("after_group") || H("group_multi"))) {
          parts.unshift(p + "{{group_column}}");
          if (H("group_multi")) parts.splice(1, 0, p + "{{group_column_2}}");
        } else if (!hasAgg() || H("select_columns") || H("alias") || hasJoin() || hasWin()) {
          if (H("self_join") && !hasAgg()) {
            parts.unshift("e.{{column_name}} AS employee", "m.{{column_name}} AS related");
          } else if ((H("join") || H("left_join") || H("right_join") || H("full_join")) && !hasAgg()) {
            parts.unshift(p + "{{column_name}}", "d.{{column_name_2}}");
          } else if (!H("all_columns")) {
            if (H("generate_series") && frm.indexOf("generate_series") !== -1) {
              /* already */
            } else {
              parts.unshift(p + "{{column_name}}");
            }
          }
        }
      }

      // 集計（タグを足すたびに列が増える）
      if (H("sum")) {
        parts.push("SUM(" + p + "{{column_name_num}})" +
          (H("filter_agg") || H("filter_clause") ? " FILTER (WHERE {{where_filter_agg}})" : "") +
          " AS total");
      }
      if (H("avg")) {
        parts.push("AVG(" + p + "{{column_name_num}})" +
          (H("filter_agg") || H("filter_clause") ? " FILTER (WHERE {{where_filter_agg}})" : "") +
          " AS avg_value");
      }
      if (H("count") ||
          (H("after_group") && !H("sum") && !H("avg") && !H("max") && !H("min")) ||
          ((H("per_group") || H("group_multi")) && !H("sum") && !H("avg") && !H("max") && !H("min") && !H("count_distinct")) ||
          ((H("filter_agg") || H("filter_clause")) && !H("sum") && !H("avg") && !H("max") && !H("min"))) {
        parts.push("COUNT(*)" +
          (H("filter_agg") || H("filter_clause") ? " FILTER (WHERE {{where_filter_agg}})" : "") +
          " AS cnt");
      }
      if (H("max")) parts.push("MAX(" + p + "{{column_name_num}}) AS max_value");
      if (H("min")) parts.push("MIN(" + p + "{{column_name_num}}) AS min_value");
      if (H("count_distinct")) {
        parts.push("COUNT(DISTINCT " + p + "{{column_name_distinct}}) AS uniq_cnt");
      }
      if (H("ratio_agg")) {
        if (H("sum") || (!H("count") && !H("avg") && !H("max") && !H("min"))) {
          if (!H("sum")) {
            parts.push("SUM(" + p + "{{column_name_num}}) AS total");
          }
          parts.push("ROUND(100.0 * SUM(" + p + "{{column_name_num}}) / NULLIF(SUM(SUM(" + p +
            "{{column_name_num}})) OVER (), 0), 2) AS pct");
        } else {
          parts.push("ROUND(100.0 * COUNT(*) / NULLIF(SUM(COUNT(*)) OVER (), 0), 2) AS pct");
        }
      }

      // ウィンドウ（1つ足すとその関数が付く）
      if (H("win_row_number") || (H("window") && !H("win_rank") && !H("win_dense_rank") &&
          !H("win_lag") && !H("win_lead") && !H("win_running_total") && !H("win_moving_avg") &&
          !H("win_group_compare"))) {
        parts.push("ROW_NUMBER() OVER (PARTITION BY " + p + "{{group_column}} ORDER BY " +
          p + "{{order_column}} {{direction}}) AS rn");
      }
      if (H("win_rank")) {
        parts.push("RANK() OVER (" +
          (H("per_group") || H("win_group_compare") ? "PARTITION BY " + p + "{{group_column}} " : "") +
          "ORDER BY " + p + "{{order_column}} {{direction}}) AS rnk");
      }
      if (H("win_dense_rank")) {
        parts.push("DENSE_RANK() OVER (ORDER BY " + p + "{{order_column}} {{direction}}) AS dense_rnk");
      }
      if (H("win_lag")) {
        parts.push("LAG(" + p + "{{column_name_num}}) OVER (ORDER BY " + p + "{{order_column}}) AS prev_value");
      }
      if (H("win_lead")) {
        parts.push("LEAD(" + p + "{{column_name_num}}) OVER (ORDER BY " + p + "{{order_column}}) AS next_value");
      }
      if (H("win_running_total")) {
        parts.push("SUM(" + p + "{{column_name_num}}) OVER (ORDER BY " + p + "{{order_column}}) AS running_total");
      }
      if (H("win_moving_avg")) {
        parts.push("AVG(" + p + "{{column_name_num}}) OVER (ORDER BY " + p +
          "{{order_column}} ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg");
      }
      if (H("win_group_compare")) {
        parts.push("AVG(" + p + "{{column_name_num}}) OVER (PARTITION BY " + p + "{{group_column}}) AS group_avg");
      }
    }

    // 重複除去
    var uniqParts = [];
    parts.forEach(function (part) {
      if (uniqParts.indexOf(part) === -1) uniqParts.push(part);
    });
    parts = uniqParts;
    if (!parts.length) parts.push(p + "{{column_name}}");

    var selectSql = "SELECT\n       " + parts.join(",\n       ");

    // WHERE（選んだ条件をすべて AND）
    var whereParts = [];
    if (H("no_match")) whereParts.push("d.{{column_name_3}} IS NULL");
    if (H("like")) whereParts.push(p + "{{column_name_search}} LIKE {{value_like}}");
    if (H("case_insensitive")) whereParts.push(p + "{{column_name_search}} ILIKE {{value_like}}");
    if (H("is_null")) whereParts.push(p + "{{column_name_null}} IS NULL");
    if (H("regex")) whereParts.push(p + "{{column_name_regex}} ~ {{value_regex}}");
    if (H("json")) whereParts.push(p + "{{column_name_json}} @> '{{value_json}}'::jsonb");
    if (H("array")) whereParts.push(p + "{{column_name_array}} @> ARRAY[{{value_array}}]");
    if (H("any_op")) whereParts.push(p + "{{column_name_any}} {{operator_any}} ANY ({{value_any}})");
    if (H("all_op")) whereParts.push(p + "{{column_name_all}} {{operator_all}} ALL ({{value_all}})");
    if (H("not_op")) whereParts.push("NOT (" + p + "{{column_name_not}} {{operator_not}} {{value_not}})");
    if (H("compare")) whereParts.push(p + "{{column_name_cmp}} {{operator}} {{value}}");
    if (H("exists")) {
      whereParts.push("EXISTS (\n  SELECT 1 FROM {{table_name_exists}} AS p\n" +
        "  WHERE p.{{column_name_exists}} = " + p + "{{column_name_exists}}\n)");
    }
    if (H("not_exists")) {
      whereParts.push("NOT EXISTS (\n  SELECT 1 FROM {{table_name_exists}} AS p\n" +
        "  WHERE p.{{column_name_exists}} = " + p + "{{column_name_exists}}\n)");
    }
    if (H("multirow_subquery")) {
      whereParts.push(p + "{{column_name_in}} IN (\n  SELECT s.{{column_name_in}}\n  FROM {{table_name_in}} AS s\n)");
    }
    if (H("scalar_subquery") || H("correlated_subquery")) {
      whereParts.push(p + "{{column_name_num}} {{operator_scalar}} (\n" +
        "  SELECT AVG(e2.{{column_name_num}})\n  FROM {{table_name}} AS e2\n" +
        "  WHERE e2.{{group_column}} = " + p + "{{group_column}}\n)");
    }
    if (H("filter") || H("compound_where")) {
      whereParts.push("{{where_condition}}");
      if (H("compound_where")) whereParts.push("{{where_condition_2}}");
    }

    var lines = [selectSql, frm];
    if (whereParts.length) lines.push("WHERE " + whereParts.join("\n  AND "));

    // GROUP BY: 「ごと」「複数列」「HAVING」で付く（割合だけなら全体1行でウィンドウ計算）
    var needGroup = H("per_group") || H("group_multi") || H("after_group");
    if (needGroup) {
      var gcols = [p + "{{group_column}}"];
      if (H("group_multi")) gcols.push(p + "{{group_column_2}}");
      if (H("lateral")) gcols.push("r.{{column_name_lat}}");
      lines.push("GROUP BY " + gcols.join(", "));
    }

    if (H("after_group")) {
      var havingExpr = H("sum") || H("ratio_agg") ? "SUM(" + p + "{{column_name_num}})" :
        H("count") ? "COUNT(*)" :
        H("avg") ? "AVG(" + p + "{{column_name_num}})" :
        H("max") ? "MAX(" + p + "{{column_name_num}})" :
        H("min") ? "MIN(" + p + "{{column_name_num}})" :
        "COUNT(*)";
      lines.push("HAVING " + havingExpr + " {{operator_having}} {{value_having}}");
    }

    if (H("sort")) {
      if (needGroup && H("sum")) lines.push("ORDER BY total {{direction}}");
      else if (needGroup && H("count")) lines.push("ORDER BY cnt {{direction}}");
      else lines.push("ORDER BY " + p + "{{order_column}} {{direction}}");
    }
    if (H("limit")) lines.push("LIMIT {{value_limit}}");

    var sql = lines.join("\n") + ";";

    if (H("recursive_cte")) {
      return "WITH RECURSIVE {{alias_name}} AS (\n" +
        "  SELECT {{column_name}} AS id, {{column_name_2}} AS parent_id, 1 AS depth\n" +
        "  FROM {{table_name}}\n  WHERE {{column_name_2}} IS NULL\n" +
        (needWhere() ? "    AND ({{where_condition}})\n" : "") +
        "  UNION ALL\n" +
        "  SELECT c.{{column_name}}, c.{{column_name_2}}, p.depth + 1\n" +
        "  FROM {{table_name}} AS c\n" +
        "  INNER JOIN {{alias_name}} AS p ON c.{{column_name_2}} = p.id\n)\n" +
        "SELECT *\nFROM {{alias_name}}" +
        (H("sort") ? "\nORDER BY depth, id" : "") +
        (H("limit") ? "\nLIMIT {{value_limit}}" : "") + ";";
    }
    if (H("multi_cte") || H("cte")) {
      var core = lines.join("\n");
      if (H("multi_cte")) {
        return "WITH {{alias_name}} AS (\n  " + core.replace(/\n/g, "\n  ") + "\n),\n" +
          "{{alias_name_2}} AS (\n  SELECT * FROM {{alias_name}}\n)\nSELECT *\nFROM {{alias_name_2}};";
      }
      return "WITH {{alias_name}} AS (\n  " + core.replace(/\n/g, "\n  ") + "\n)\nSELECT *\nFROM {{alias_name}};";
    }

    return sql;
  }
}
